# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T5ZcpzyZeuXYrt_HGoyAkS5aiy0npiFQ
"""

import numpy as np
def sphere(x):
    d=x.shape[0]
    sum=0
    for i in range(d):
      sum=sum+x[i]**2
    return sum
x=np.array([1,2,3])
print(sphere(x))

